# Change these first
owner: elemilio # Your GitHub organization or username, where this repository lives
repo: uptime_lio # The name of this repository

sites:
  - name: bcn.cat
    url: https://bcn.cat
    icon: https://www.barcelona.cat/favicon.ico
  - name: Espaidocs (Owncloud)
    url: https://espaidocs.bcn.cat
  - name: Comunitats (HumHub)
    url: https://comunitats.bcn.cat/index.php?r=user%2Fauth%2Flogin
  - name: GitLab DTI
    url: https://gitlab.dtibcn.cat/users/sign_in

assignees:
  - elemilio

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime_lio
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitorització DTI"
  introMessage: Status page
  navbar:
    - title: Home
      href: /

  theme: night

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/1 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
