# Change these first
owner: elemilio # Your GitHub organization or username, where this repository lives
repo: uptime_lio # The name of this repository

sites:
  - name: bcn.cat
    url: https://bcn.cat
    icon: https://www.barcelona.cat/favicon.ico
  - name: Espaidocs (Owncloud)
    url: https://espaidocs.bcn.cat
    icon: https://espaidocs.bcn.cat/core/img/favicon.ico
  - name: Comunitats (HumHub)
    url: https://comunitats.bcn.cat/index.php?r=user%2Fauth%2Flogin
    icon: https://comunitats.bcn.cat/themes/HumHub/ico/favicon-32x32.png
  - name: GitLab DTI
    url: https://gitlab.dtibcn.cat/users/sign_in
    icon: https://gitlab.dtibcn.cat/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png
  - name: El Digital
    url: https://eldigital.barcelona.cat/admin-wp
    icon: https://www.barcelona.cat/favicon.ico
  - name: Districtes (Sant Martí)
    url: https://ajuntament.barcelona.cat/santmarti/ca
    icon: https://www.barcelona.cat/favicon.ico
  - name: www.barcelona.cat (CONTINGUTS)
    url: https://continguts-www.barcelona.cat/ca
    icon: https://www.barcelona.cat/favicon.ico

assignees:
  - emiliobaena

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime_lio
  logoUrl: https://static.thenounproject.com/png/2426100-200.png
  name: Upptime
  introTitle: "Status Canals Digitals"
  introMessage: Status page
  navbar:
    - title: Home
      href: /

  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
